# Generated by Django 5.2.3 on 2025-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='salt',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
