# Generated by Django 5.2.3 on 2025-06-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_passwordentry_salt_vaultsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentry',
            name='salt',
        ),
    ]
